#!/usr/bin/python3
import asyncio
from aiohttp import web
from broca.reaper import reaper
from broca.rpc import app
from configparser import ConfigParser

host = "127.0.0.1"
port = 9091

config = ConfigParser()
paths = [ "broca.ini", "/etc/broca.ini" ]
for path in paths:
    try:
        with open(path) as f:
            config.readfp(f)
        host = config.get("broca", "host")
        port = int(config.get("broca", "port"))
    except FileNotFoundError:
        pass

asyncio.ensure_future(reaper())
web.run_app(app, host=host, port=port)
